apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Release.Name }}-{{ .Values.database.name }}-service
  name: {{ .Release.Name }}-{{ .Values.database.name }}-service
spec:
  type: ExternalName
  externalName: {{ .Values.database.externalName }}